//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARY_PROJECT_4._0.LibraryModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> CategorieID { get; set; }
        public Nullable<int> AutorID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual Status Status { get; set; }
    }
}
